### ISSUE TITLE
Code cannot run

### ISSUE THREAD

**Issue by Sinking-Stone** [CryptoLabInc/HETAL#1]
I have installed all environment dependencies as required by `README.md`. But when I executed the command `python run.py --data mnist --generate_keys --encrypted_train --early_stopping`, the following error occurred.
![图片](https://github.com/CryptoLabInc/HETAL/assets/89176650/a829714b-79b3-4535-b935-a72dc5387b1f)
The specific location where the error occurred is the file `run. py`
![图片](https://github.com/CryptoLabInc/HETAL/assets/89176650/261cbe6a-2bdd-4de4-bed4-5bfa02b765a4)

**Comment by seewoolee-cryptolab** [comment]
Hi, sorry for the late reply. Based on translator, your Chinese error message translates as "Illegal instruction (core dumped)", is this right? (We can't read Chinese, so please add more explanations in English). Additionally, our code only runs in the following environments:
- OS: Linux
- Memory: minimum 16GB (recommended: 32GB)

Could you also provide your environment's information - OS, CPU, and memory? Thank you.

**Comment by Sinking-Stone** [comment]
Yes, it is "Illegal instruction (core dumped)". My operating system is `Ubuntu 18.04.4 LTS`, CPU: `Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz`, memory: `64G`. I hope to obtain the GPU version of heaan mentioned in the [paper](https://proceedings.mlr.press/v202/lee23m.html), thank you.

**Comment by seewoolee-cryptolab** [comment]
Hi, we were able to reproduce the problem, and we update the `.whl` files in #5. Let me know if there's still an issue with new file.
Also, if you want to use GPU version, contact `stat@cryptolab.co.kr`.

**Comment by Sinking-Stone** [comment]
Thank you. The problem has been resolved and the program can now run normally.
