### ISSUE TITLE
Question about Classifier model and bootstrapping.

### ISSUE THREAD

**Issue by jqxue1999** [CryptoLabInc/HETAL#8]
Awesome project! I have successfully run the code.

However, when I want to devle into the details of "hml.Classifier", I cannot find any information beside [this](https://heaan.it/docs/stat/python/logistic_reg.html). 

I'd like to know the encrypted training details like how many **bootstrapping** it uses, but I cannot identify the source code of hml.Classifier.

Thanks in advance for your reply!

**Comment by seewoolee-cryptolab** [comment]
Hi, unfortunately, such a functionality is not supported yet in the current HEaaN.SDK (or this HETAL version), but might be added in the future.

**Comment by jqxue1999** [comment]
Thanks for your reply
